export const SELECT_SCHOOL = 'SELECT_SCHOOL';
export const INVALIDATE_SCHOOL = 'INVALIDATE_SCHOOL';

// API actions
export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const RECEIVE_EVENTS_FAILURE = 'RECEIVE_EVENTS_FAILURE';
