# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Scavenge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Scavenge
  pod 'MobileCenter/Crashes', '~> 0.12.1'
  pod 'MobileCenter/Analytics', '~> 0.12.1'
  pod 'RNMobileCenterShared', '~> 0.9.0'

  

  target 'ScavengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Scavenge-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Scavenge-tvOS

  target 'Scavenge-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
